const todoArr = [
  {
    id: 1,
    name: "wash car",
    dueDate: "2021-12-11",
    expectedTime: 15,
    deps: "water, car",
    excitement: "low",
    completed: true,
  },
  {
    id: 2,
    name: "buy new TV",
    dueDate: '2022-12-11',
    expectedTime: 60,
    deps: "money",
    excitement: "high",
    completed: false,
  },
  {
    id: 3,
    name: "visit mom",
    dueDate: '2021-12-31',
    expectedTime: 360,
    deps: "free time",
    excitement: "high",
    completed: false,
  },
  {
    id: 4,
    name: "learn new framework",
    dueDate: '2022-05-01',
    expectedTime: 10000,
    deps: "free time, pc",
    excitement: "high",
    completed: false,
  },
  {
    id: 5,
    name: "repair bicycle",
    dueDate: "2021-12-05",
    expectedTime: 60,
    deps: "bicycle, tools",
    excitement: "medium",
    completed: false,
  },
  {
    id: 6,
    name: "talk with Ted",
    dueDate: '2021-11-30',
    expectedTime: 40,
    deps: "free time, Ted",
    excitement: "low",
    completed: false,
  },
  {
    id: 7,
    name: "go fishing with Sam",
    dueDate: '2022-05-05',
    expectedTime: 360,
    deps: "boat, fishing tools, Sam",
    excitement: "high",
    completed: false,
  },
  {
    id: 8,
    name: "cook dinner",
    dueDate: '2021-11-28',
    expectedTime: 120,
    deps: "chicken, potato",
    excitement: 'low',
    completed: false,
  },
  {
    id: 9,
    name: "buy vegetables",
    dueDate: '2021-11-30',
    expectedTime: 60,
    deps: "money",
    excitement: 'low',
    completed: false,
  },
  {
    id: 10,
    name: "choose a gift for Xmas",
    dueDate: '2021-11-30',
    expectedTime: 120,
    deps: "money",
    excitement: 'high',
    completed: false,
  },
];

export default todoArr;
